### ISSUE TITLE
Do not know why？

### ISSUE THREAD

**Issue by SPECRTUM** [saicaca/fuwari#122]
First time playing with this, don't know where the problem is
Dev     normal
Build   error
![SharedScreenshot](https://github.com/saicaca/fuwari/assets/28756320/29ae4752-657f-49e6-ba9f-fe99c890dc61)

**Comment by James-Heller** [comment]
Maybe you need to learn some basic Typescript knowledge

**Comment by flaymes** [comment]
just remove `astro check` in package.json

**Comment by saicaca** [comment]
Don't run `astro check` for now, as the project won't pass it due to:
1. My TypeScript skills suck. There are a bunch of errors in the codes and I need some time to fix them.
2. The package [astro-icon](https://github.com/natemoo-re/astro-icon/) used in the project only accepts numbers for the `size` parameter, but I do need to use strings here. There’s already a PR to allow strings but it hasn’t been merged yet.

**Comment by saicaca** [comment]
Okay, I found a workaround for this 96223c0b5a4f7ed8eb88bfb876e85af58cf9ebad. The `astro check` should no longer fail now.
