### ISSUE TITLE
Support Image Zoom on Posts

### ISSUE THREAD

**Issue by dabuside** [saicaca/fuwari#131]
Implementing image zoom functionality would be really helpful, especially when large images are inserted into a post. 

https://ant.design/components/image#examples

[screencast-ant_design-2024_07_21-15_10_34.webm](https://github.com/user-attachments/assets/e39ebf42-82cb-4652-814f-a417ae16678b)

I am willing to submit a pull request to add this feature.

**Comment by saicaca** [comment]
Thank you for your support! This is exactly what I want to implement.

My plan is to implement this with [PhotoSwipe](https://github.com/dimsemenov/photoswipe) rather than introducing another UI framework. I currently don’t have enough time for it. If you are willing to help I would greatly appreciate it.

FYR:
- https://photoswipe.com/getting-started/
- https://dev.to/petrovicz/astro-photoswipe-549a
