### ISSUE TITLE
Changing avatar image results in "files[normalizedPath] is not a function" Error

### ISSUE THREAD

**Issue by Lakeberries** [saicaca/fuwari#20]
I'm trying to change the avatar image, but when using an image source other than the demo, this error shows:
` files[normalizedPath] is not a function`
at `misc/ImageWrapper.astro:23:38`
and I can't figure out how to solve this.
this theme looks amazing btw!

**Comment by saicaca** [comment]
Thank you for your support!

This error usually occurs because the image cannot be found at the given path. Please check if the image path you entered is correct.
1. If the path starts with `/`, then this path is relative to the /public directory.
2. Otherwise, the path is relative to the /src directory.

I hope this will solve the problem.

**Comment by Lakeberries** [comment]
hi again!
my image is in /src/images/avatar.png

src/assets/images/avatar.png = error
assets/images/avatar.png = error

i have tried moving the image to the public directory, this is what happens
/public/avatar.png = error
/avatar.png = error

**Comment by Lakeberries** [comment]
this is weird, everything seems to work fine if i clone the theme again and start over. guess ill just do that
