### ISSUE TITLE
[Bug] The theme is loaded twice

### ISSUE THREAD

**Issue by JoeyC-Dev** [saicaca/fuwari#46]
Initially, I found this code in the src:
https://github.com/saicaca/fuwari/blob/main/src/layouts/Layout.astro#L211
```
function loadTheme() {
	if (localStorage.theme === 'dark' || (!('theme' in localStorage) &&
		window.matchMedia('(prefers-color-scheme: dark)').matches)) {
		document.documentElement.classList.add('dark');
		localStorage.theme = 'dark';
	} else {
		document.documentElement.classList.remove('dark');
		localStorage.theme = 'light';
	}
}
```

I understand this is a feature to confirm which theme the user want to use, so the blog can be  presented with corresponding theme by `localStorage.theme = 'light/dark';`
Also, `document.documentElement.classList.add('dark');` must be for changing the theme. 

But there are some issues here: 
1. If users' network is not fast enough (or their computer has slow performance), and they use dark theme, it will splash a light theme and then switch the dark theme seconds later. It is also reproduceable on the current demo preview site. This can be a very bad experience.  
**To reproduce:** change throttling setting in F12 to "Slow 3G". 
2. IMO, I don't think store `theme` permanently for user is good experience. Because when user switch theme systemwide, the blog will not automatically change the theme accordingly by this design. For this, I made the PR with a new feature: https://github.com/saicaca/fuwari/pull/45

**Comment by saicaca** [comment]
Thanks for your suggestion. It should be fixed in #71.

For the first issue, I add the class `dark` to the root element. Now users with dark mode won't see a bright splash screen.

For the second issue, users can now manually select `follow system`, which is also the default setting for new visitors. I prefer not to make the default setting configurable, since I think it's not a good user experience to force new visitors to use either light or dark mode, instead of using the system settings. So I am closing #67.

**Comment by JoeyC-Dev** [comment]
@saicaca Thank you for fixing the issue.
But it looks like the way you fix it is to force initial load as "dark mode". This is my first time visiting that preview link:
![image](https://github.com/saicaca/fuwari/assets/142381267/0921bda0-7247-49ef-ac7e-209f5e54f8c1)

Hence, the bug exists in the opposite way now: 
Originally, the dark theme user will see light theme first then switch the dark theme. But now, the light theme user will see dark theme first, then can get the light theme.

For the second part, IMO, it is up to how blogger wants, not how user wants. In the end, it is the blogger deploy the theme not the users. Anyway, it is up to you.

**Comment by saicaca** [comment]
Thank you for your feedback!

You are right, the previous fix just reversed the bug, since I think letting light-mode users see a dark screen is at least better than the other way around. 8ce1c7ab6e26b632628cc158b2a21cac44911b2e should have completely fixed the problem. The theme is now set before the webpage is displayed.

About the other issue, I understand bloggers might want to set a different default theme, but I really don't encourage doing so, as I believe the automatic mode always provides the best user experience for new visitors. For these kinds of settings, I prefer not to place them in `config.ts`. I am considering putting them to an "Advanced Settings" or somewhere else. Currently, they can be edited in `constants.ts`.
